name: Code Quality

on:
  - pull_request
  - push

jobs:
  coding-guidelines:
    name: Coding Guidelines (php-cs-fixer)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instal PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: php-cs-fixer:3.54.0

      - name: Run friendsofphp/php-cs-fixer
        run: php-cs-fixer fix --diff --dry-run --show-progress=dots --using-cache=no --verbose

  type-checker:
    name: Type Checker (vimeo/psalm)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: composer:v2

      - name: Update dependencies with composer
        run: |
          composer update --no-interaction --no-ansi --no-progress
          composer bin psalm update --no-interaction --no-ansi --no-progress

      - name: Run vimeo/psalm on packages
        run: bin/psalm --no-progress --shepherd --show-info=true --stats
