name: Unit Tests

on:
  - pull_request
  - push

env:
   # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: "dev-master"

jobs:
  unit_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php-version:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
        dependencies:
          - lowest
          - highest

    name: logic (${{ matrix.os }}:PHP-${{ matrix.php-version }}:${{ matrix.dependencies }})
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          tools: composer:v2

      - run: composer --version

      - if: matrix.dependencies == 'highest'
        run: composer update --no-interaction --no-progress --no-ansi

      - if: matrix.dependencies == 'lowest'
        run: composer update --no-interaction --no-progress --no-ansi --prefer-lowest

      - run: composer bin phpunit update --no-interaction --no-progress --no-ansi

      - run: bin/phpunit

      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
